# Generated by Django 4.0.5 on 2022-06-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_alter_post_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
